# Generated by Django 3.1.5 on 2021-04-03 17:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('general', '0001_initial'), ('general', '0002_auto_20210325_0054'), ('general', '0003_auto_20210325_0106'), ('general', '0004_auto_20210325_0945'), ('general', '0005_auto_20210325_0946'), ('general', '0006_auto_20210325_0951'), ('general', '0007_auto_20210325_0953'), ('general', '0008_auto_20210329_1201'), ('general', '0009_remove_organization_score'), ('general', '0010_organization_score'), ('general', '0011_organization_commentscount'), ('general', '0012_auto_20210403_2352'), ('general', '0013_auto_20210404_0014'), ('general', '0014_auto_20210404_0036'), ('general', '0015_auto_20210404_0045')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InternPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=200, null=True)),
                ('organizationType', models.CharField(choices=[('各級學校諮商', '各級學校諮商'), ('社區性心理衛生中心或諮商機構', '社區性心理衛生中心或諮商機構'), ('已立案之社會福利相關機構', '已立案之社會福利相關機構'), ('醫療機構', '醫療機構'), ('司法院或法務部所屬相關單位', '司法院或法務部所屬相關單位'), ('企業單位及所屬基金會', '企業單位及所屬基金會')], max_length=200, null=True)),
                ('commentsCount', models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('score', models.FloatField(default=0, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='HashTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(blank=True, max_length=200, null=True)),
                ('createDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('intern', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.internPerson')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.organization')),
                ('internshipType', models.CharField(choices=[('校外課程實習', '校外課程實習'), ('校外全職實習', '校外全職實習'), ('校內課程實習', '校內課程實習'), ('校內全職實習', '校內全職實習')], max_length=200, null=True)),
                ('hashTags', models.ManyToManyField(blank=True, to='general.HashTags')),
                ('score', models.IntegerField(default=0, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
