# Generated by Django 3.1.5 on 2021-04-06 02:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HashTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='InternPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('profilePic', models.ImageField(blank=True, default='default.png', null=True, upload_to='')),
                ('createDate', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=200, null=True)),
                ('organizationType', models.CharField(choices=[('各級學校諮商', '各級學校諮商'), ('社區性心理衛生中心或諮商機構', '社區性心理衛生中心或諮商機構'), ('已立案之社會福利相關機構', '已立案之社會福利相關機構'), ('醫療機構', '醫療機構'), ('司法院或法務部所屬相關單位', '司法院或法務部所屬相關單位'), ('企業單位及所屬基金會', '企業單位及所屬基金會')], max_length=200, null=True)),
                ('score', models.FloatField(default=0, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('commentsCount', models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internshipType', models.CharField(choices=[('校外課程實習', '校外課程實習'), ('校外全職實習', '校外全職實習'), ('校內課程實習', '校內課程實習'), ('校內全職實習', '校內全職實習')], max_length=200, null=True)),
                ('comments', models.CharField(blank=True, max_length=200, null=True)),
                ('createDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('score', models.IntegerField(default=0, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('hashTags', models.ManyToManyField(blank=True, to='general.HashTags')),
                ('intern', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.internperson')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.organization')),
            ],
        ),
    ]
