# Generated by Django 3.1.5 on 2021-04-06 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internperson',
            name='profilePic',
        ),
    ]
