# Generated by Django 3.1.5 on 2021-04-06 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_remove_internperson_profilepic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='commentsCount',
        ),
        migrations.AddField(
            model_name='internperson',
            name='profilePic',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
    ]
