# Generated by Django 3.1.5 on 2021-03-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_auto_20210325_0054'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='hashTags',
        ),
        migrations.AddField(
            model_name='comment',
            name='hashTags',
            field=models.ManyToManyField(to='general.HashTags'),
        ),
    ]
