# Generated by Django 3.1.5 on 2021-04-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_internperson_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='internperson',
            name='createDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='internperson',
            name='profilePic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
