# Generated by Django 3.1.5 on 2021-04-06 02:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_auto_20210406_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='commentsCount',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
