# Generated by Django 3.1.5 on 2021-03-25 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_auto_20210325_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='hashTags',
            field=models.ManyToManyField(blank=True, to='general.HashTags'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='internshipType',
            field=models.CharField(choices=[('校外課程實習', '校外課程實習'), ('校外全職實習', '校外全職實習'), ('校內課程實習', '校內課程實習'), ('校內全職實習', '校內全職實習')], max_length=200, null=True),
        ),
    ]
