# Generated by Django 3.1.5 on 2021-04-12 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_internperson_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='detailInfoFromExtUrl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='hashTags',
            field=models.ManyToManyField(blank=True, to='general.HashTags'),
        ),
        migrations.AddField(
            model_name='organization',
            name='internshipContent',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='subsidy',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
