# Generated by Django 3.1.5 on 2021-04-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_auto_20210412_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='detailInfoFromExtUrl',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
