# Generated by Django 3.1.5 on 2021-04-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0008_auto_20210412_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='organizationType',
            field=models.CharField(choices=[('大專校院諮商(輔導)中心(處、室、組)', '大專校院諮商(輔導)中心(處、室、組)'), ('心理諮商所', '心理諮商所'), ('公、私立高中、職、中小學輔導室（處）、教育局處學生諮商中心', '公、私立高中、職、中小學輔導室（處）、教育局處學生諮商中心'), ('醫療機構', '醫療機構'), ('社區性心理衛生中心', '社區性心理衛生中心'), ('政府及事業單位設有心理治療或諮商業務之單位', '政府及事業單位設有心理治療或諮商業務之單位'), ('財團法人基金會', '財團法人基金會')], max_length=200, null=True),
        ),
    ]
