# Generated by Django 3.1.5 on 2021-04-19 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0009_auto_20210412_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='isApprove',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
