# Generated by Django 3.1.5 on 2021-04-27 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0012_remove_comment_updateddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='updatedDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
