# Generated by Django 3.1.5 on 2021-04-27 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0013_comment_updateddate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voteType', models.CharField(choices=[('同意', '同意'), ('沒意見', '沒意見'), ('不同意', '不同意')], max_length=200, null=True)),
                ('createDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('intern', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.internperson')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='votes',
            field=models.ManyToManyField(blank=True, to='general.Votes'),
        ),
    ]
