# Generated by Django 3.1.5 on 2021-04-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0014_auto_20210427_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='voteType',
            field=models.CharField(choices=[('agree', 'agree'), ('neutral', 'neutral'), ('disagree', 'disagree')], max_length=200, null=True),
        ),
    ]
