# Generated by Django 3.2 on 2021-04-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0015_auto_20210427_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='voteType',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
